### ISSUE TITLE
Incomplete .ics formatting on icwrite()

### ISSUE THREAD

**Issue by RobertJDReid** [ATFutures/calendar#40] opened 2021-04-20 19:37 UTC
ic_write() fails to append 'BEGIN:VCALENDAR’ as first line of a .ics file.

_____ Session info ________

 version  R version 4.0.3 (2020-10-10)
 os       macOS Catalina 10.15.7      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2021-04-20                  

 calendar    * 0.0.1   2019-02-11 [1] CRAN (R 4.0.2)

**Comment by Robinlovelace** [comment] 2021-04-20 19:42
Thanks for reporting @RobertJDReid but I cannot reproduce the behaviour. Can you provide a reproducible example?

Reproducible example of it working:

``` r
install.packages("calendar")
#> Installing package into '/home/robin/R/x86_64-pc-linux-gnu-library/4.0'
#> (as 'lib' is unspecified)
library(calendar)
?ic_write
ic <- ical(ical_example)
f = tempfile(fileext = ".ics")
ic_write(ic, f)
readLines(f)
#>  [1] "BEGIN:VCALENDAR"                                  
#>  [2] "PRODID:-//Google Inc//Google Calendar 70.9054//EN"
#>  [3] "VERSION:2.0"                                      
#>  [4] "CALSCALE:GREGORIAN"                               
#>  [5] "METHOD:PUBLISH"                                   
#>  [6] "X-WR-CALNAME:atf-test"                            
#>  [7] "X-WR-TIMEZONE:Europe/London"                      
#>  [8] "BEGIN:VEVENT"                                     
#>  [9] "DTSTART:20180809T160000"                          
#> [10] "DTEND:20180809T163000"                            
#> [11] "DTSTAMP:20180810T094100Z"                         
#> [12] "UID:1119ejg4vug5758527atjcrqj3@google.com"        
#> [13] "CREATED:20180807T133712Z"                         
#> [14] "DESCRIPTION:\\n"                                  
#> [15] "LAST-MODIFIED:20180807T133712Z"                   
#> [16] "LOCATION:"                                        
#> [17] "SEQUENCE:0"                                       
#> [18] "STATUS:CONFIRMED"                                 
#> [19] "SUMMARY:ical programming mission"                 
#> [20] "TRANSP:OPAQUE"                                    
#> [21] "END:VEVENT"                                       
#> [22] "END:VCALENDAR"
```

<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by RobertJDReid** [comment] 2021-04-20 22:41
Here is a REPREX for the behavior I am seeing. On my system it formats a .ics file that is missing "BEGIN:VCALENDAR" as the first line of the file. Adding that line will allow calendar import. But perhaps ic_write was never meant to work this way?

library(calendar)
events <- data.frame(SUMMARY = c("event 1","event 2"),
                     DTSTART = c(as.POSIXct(Sys.time()),as.POSIXct(Sys.time() + 3600)),
                     DTEND   = c(as.POSIXct(Sys.time() + 1800),as.POSIXct(Sys.time() + 5400)),
                     UID     = c(ic_guid(),ic_guid())
)
ic_write(events,"events.ics")

**Comment by Robinlovelace** [comment] 2021-04-21 08:13
``` r
library(calendar)
events <- data.frame(SUMMARY = c("event 1","event 2"),
                     DTSTART = c(as.POSIXct(Sys.time()),as.POSIXct(Sys.time() + 3600)),
                     DTEND = c(as.POSIXct(Sys.time() + 1800),as.POSIXct(Sys.time() + 5400)),
                     UID = c(ic_guid(),ic_guid())
)
ic_write(events,"events.ics")
readLines("events.ics")
#>  [1] "BEGIN:VEVENT"                                 
#>  [2] "SUMMARY:event 1"                              
#>  [3] "DTSTART:20210421T091258"                      
#>  [4] "DTEND:20210421T094258"                        
#>  [5] "UID:ical-a50568b2-0f94-4554-a2a8-57109cc40042"
#>  [6] "END:VEVENT"                                   
#>  [7] "BEGIN:VEVENT"                                 
#>  [8] "SUMMARY:event 2"                              
#>  [9] "DTSTART:20210421T101258"                      
#> [10] "DTEND:20210421T104258"                        
#> [11] "UID:ical-55906701-e5c4-48f6-8fcb-2e4788d38be3"
#> [12] "END:VEVENT"                                   
#> [13] "END:VCALENDAR"
```

<sup>Created on 2021-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Robinlovelace** [comment] 2021-04-21 08:13
Confirmed.

**Comment by Robinlovelace** [comment] 2021-04-21 10:43
Anyone fancy taking a gander. @layik ? Would like to revive this thing, it's a fun and potentially useful package.

**Comment by layik** [comment] 2021-06-20 21:12
Right, I just saw or remembered this mention. Either my setup has some issues documenting the package properly or the last commit I inherited had not documented the package properly. It might fail CRAN as it is but happy to address that later. I think the only line that was missing is now in. Thanks for reporting @RobertJDReid.

**Comment by layik** [comment] 2021-06-20 22:05
Will have to have another go at some other time. Sorry for lack of response on this.

**Comment by ConorIA** [comment] 2021-06-29 13:57
Just thought that I would add to this. I whipped up a sunrise / sunset calendar using the package (thanks!) 

I validated the .ics file on https://icalendar.org/validator.html. This was my workaround to the missing info: 

```
ic_write(cal, 'test.ics') # Write the file
ics <- readLines("test.ics") # Read it back in again
ics[stringr::str_detect(ics, "^DT(START|END)")] <- paste0(ics[stringr::str_detect(ics, "^DT(START|END)")], "Z") # Unrelated / see NOTE 1
writeLines(c("BEGIN:VCALENDAR", "PRODID:-//Conr.ca//Suntimes//EN", "VERSION:2.0", ics), "test.ics") # See Note 2
```

**NOTE 1:** My times were in UTC, so I had to manually set them to Zulu to avoid "floating" events with no timezone specified. There is a "zulu" flag in `ic_char_datetime()`, but this is not exposed to `ic_write()`. Recommend adding dots `...` to `ic_write()` that would optionally pass `zulu = TRUE` down the line. 

**NOTE 2:** The ICS file is missing two [required properties](https://icalendar.org/iCalendar-RFC-5545/3-6-calendar-components.html) "[PRODID](https://icalendar.org/iCalendar-RFC-5545/3-7-3-product-identifier.html)" and "[VERSION](https://icalendar.org/iCalendar-RFC-5545/3-7-4-version.html)". These should probably be use-configurable strings added to `ic_write()`.

**Comment by Robinlovelace** [comment] 2021-07-15 06:30
Thanks @ConorIA, this is useful. I do think these should be a quick fix and fully advocate fixing them. A PR would be most welcome. Otherwise myself or @layik will look to get a quick fix in when we have a spare moment. Sorry for the slow responses, I see you made this useful comment 2 weeks ago!

It's been a long time since I looked at the code. Would this be where the change is needed?

https://github.com/ATFutures/calendar/blob/41a527a7d9fc89fc11bbed2bf03a30434f1b824c/R/ical.R#L54-L83

**Comment by ConorIA** [comment] 2021-07-15 12:25
Thanks for your reply @Robinlovelace.

It turned out that the error was more a user error than a package error. I had passed a "normal" tibble to ic_write, which meant that it was never getting ic_attributes, therefore the start of the file was "cut off" (NULL was printed instead of BEGIN ...".

To solve this (#41), I check if the ic object in ic_write is an ical object and coerce it to one if not. I added ic_attributes for a one-stop shop. As I am writing this, I wonder if a better way to do this maybe to spit out a warning if the ic object is not an ical. i.e. it would remind users to use:
`ic_write(ical(cal, ic_attributes = blah))` instead of what I have done, which is `ic_write(cal, ic_attributes = blah)`. 
It depends on whether keeping the number of arguments in `ic_write` low is a priority. 

I also passed zulu up the chain ic_char_datetime -> ic_char_events -> ic_character -> ic_write. I thought about using the three dots for this, but I figured it is cleaner to be explicit.

**Comment by Robinlovelace** [comment] 2021-07-16 05:57
Fantastic, many thanks Conor, great to see the link to your code. I have merged your PR and will now update the news. Also good to see a plumber API in action, one I'm sure @layik will be interested in (we've talked about creating APIs for serving geo data a harder thing I think).

**Comment by ConorIA** [comment] 2021-07-16 12:03
Hi Robin, 

Plumber is fantastic and you can really serve arbitrary data by using e.g. `serialize()` and `base64_enc()`

I have a tool that goes the other way - spatial data is submitted _to_ the API via httr:

Pt1: https://gitlab.com/ConorIA/conjuntool/-/blob/devel/shiny/server.R#L642
Pt1: https://gitlab.com/ConorIA/conjuntool/-/blob/devel/shiny/R/crop_req.R#L4

And is processed in the crop endpoint here: https://gitlab.com/ConorIA/conjuntool/-/blob/devel/plumber/api/plumber.R#L304

If you are getting the data into R, you could go the other way and serialize into binary in plumber and decode in R. That same plumber file also shows how you could use an intermediary WebDAV server if you need to do some long running processing (i.e. files won't be served right away). 

P.S. I think this issue can be closed. 😉

**Closed** 2021-07-16 12:12 UTC
